name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # - name: Print values
    #   run: |
    #     echo test
    #     echo ${{ secrets.GCP_SA_KEY }}
        


    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT }}

    

    - name: Authenticate Docker with GCP
      run: |
        echo ${{ secrets.GCP_SA_KEY }} | docker login -u _json_key --password-stdin https://gcr.io

    # - name: Build and Push Docker Image
    #   run: |
    #     docker build -t gcr.io/${{ secrets.GCP_PROJECT }}/flask-app:latest .
    #     docker push gcr.io/${{ secrets.GCP_PROJECT }}/flask-app:latest

    # - name: Deploy to Cloud Run
    #   run: |
    #     gcloud run deploy flask-app \
    #     --image gcr.io/${{ secrets.GCP_PROJECT }}/flask-app:latest \
    #     --platform managed \
    #     --region ${{ secrets.GCP_REGION }} \
    #     --allow-unauthenticated