name: Deploy to GCP

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Authenticate Docker to Google Container Registry (GCR)
      run: |
        echo "${{ secrets.GCP_SA_KEY }}" | docker login -u _json_key --password-stdin https://gcr.io

    # - name: Build and push Docker image to GCR
    #   run: |
    #     IMAGE=gcr.io/${{ secrets.GCP_PROJECT_ID }}/flask-app:$GITHUB_SHA
    #     docker build -t $IMAGE .
    #     docker push $IMAGE

    # - name: Deploy to GCP Compute Engine (or Kubernetes Engine)
    #   run: |
    #     # Your deployment commands, such as gcloud run deploy for Cloud Run, or kubectl for GKE