# name: Deploy to cloud run

# on:
#   push:
#     branches:
#       - main
    
# jobs:
#   dockerize-and-deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v2
      
#       - name: Google Cloud Auth
#         uses: 'google-github-actions/auth@v2'
#         with:
#           credentials_json: '${{ secrets.GCP_SA_KEY }}'
#           project_id: '${{  }}'