name: Deploy to GCR and GCP

on:
  push:
    branches:
      - main  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Adjust to your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Docker image
        run: |
          printf '%s' "${{ secrets.GCP_SA_KEY }}" > gcp-key.json
          gcloud auth activate-service-account --key-file=gcp-key.json
          gcloud config set project ${{ secrets.GCP_PROJECT }}
          gcloud auth configure-docker

          docker build -t ${{ secrets.GCR_IMAGE }} .

      - name: Push Docker image to GCR
        run: |
          docker push ${{ secrets.GCR_IMAGE }}

      - name: Deploy to GCP
        run: |
          gcloud run deploy python-app-v1 \
            --image ${{ secrets.GCR_IMAGE }} \
            --platform managed \
            --region ${{ secrets.GCP_REGION }} \
            --allow-unauthenticated  # Modify as necessary